import "./globals.css";
import { Providers } from "./providers";
import Nav from "../components/Nav";
import { raleway } from "../utils/fonts";
import { CartContextProvider } from "@/components/context/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-primary">
      <body className={`${raleway.className} min-h-screen text-secondary`}>
        <CartContextProvider>
          <Providers>
            <Nav />
            {children}
          </Providers>
        </CartContextProvider>
      </body>
    </html>
  );
}
