import "./globals.css";
import {Providers} from "./providers";
import Nav from "./components/Nav";
import { raleway } from "./utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-primary">
      <body className={`${raleway.className} max-w-[1366px] mx-auto min-h-screen text-secondary px-20`}>
        <Providers>
          <Nav />
            {children}
          </Providers>
        </body>
    </html>
  );
}
